build: false

environment:
    PYTHON: "C:\\Python38-x64"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
          CONAN_VISUAL_VERSIONS: 17
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
